EP3/config/routes.rb
Rails.application.routes.draw do
 
   resources :homes
  devise_for :users

  resources :lojas do
  	resources :reviews
  end 	
  # root 'lojas#index'

  root 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

EP3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

EP3/app/models/home.rb
class Home < ApplicationRecord
end

EP3/app/models/loja.rb
class Loja < ApplicationRecord
	belongs_to :user
	has_many :reviews

end

EP3/app/models/post.rb
class Post < ApplicationRecord
end

EP3/app/models/review.rb
class Review < ApplicationRecord

	belongs_to :loja
	belongs_to :user

end

EP3/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 	has_many :lojas
 	has_many :reviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

EP3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

EP3/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

EP3/app/controllers/lojas_controller.rb
class LojasController < ApplicationController

before_action :achar_loja, only: [:show, :edit , :update, :destroy]
before_action :authenticate_user!, only: [:new, :edit]

def index
	@lojas = Loja.all.order("nome ASC")
end

def show 
	if @loja.reviews.blank?
		@average_review = 0
	else
		@average_review = @loja.reviews.average(:rating).round(2)
	end
end

def new
	@loja = Loja.new
end

def create
	@loja = Loja.new(loja_params)

	if @loja.save
		redirect_to root_path
	else
		render 'new'
	end
end

def edit
end

def update
	if @loja.update(loja_params)
		redirect_to loja_path(@loja)
	else
		render 'edit'
	end	

end

def destroy
	@loja.destroy
	redirect_to lojas_path
end

private

	def loja_params
		params.require(:loja).permit(:nome, :descricao,:email)
	end

	def achar_loja
		@loja = Loja.find(params[:id])
	end


end

EP3/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :comentario, :data)
    end
end

EP3/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :achar_loja
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

  	def new
		@review = Review.new
	end


	def create
		@review = Review.new(review_params)
		@review.loja_id = @loja.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to loja_path(@loja)
		else	
			render 'new'	
		end

	end

	def edit
	end

	def update

		if @review.update(review_params)
			redirect_to loja_path(@loja)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to loja_path(@loja)
	end


	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def achar_loja
			@loja = Loja.find(params[:loja_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end
end

EP3/app/helpers/application_helper.rb
module ApplicationHelper
end

EP3/app/helpers/homes_helper.rb
module HomesHelper
end

EP3/app/helpers/lojas_helper.rb
module LojasHelper
end

EP3/app/helpers/posts_helper.rb
module PostsHelper
end

EP3/app/helpers/reclamas_helper.rb
module ReclamasHelper
end

EP3/app/helpers/reviews_helper.rb
module ReviewsHelper
end

EP3/app/views/homes/_form.html.erb
<%= simple_form_for @home, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                homes_path, :class => 'btn btn-default' %>
<% end %>

EP3/app/views/homes/edit.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

EP3/app/views/homes/new.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

EP3/app/views/homes/show.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              homes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_home_path(@home), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              home_path(@home),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

EP3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EP3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Tá Tudo Errado!</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Como funciona?<span class="sr-only">(current)</span></a></li>
        <li><a href="/lojas">Lojas</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastro<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href= "/users/sign_up">Cadastrar Usuário</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/lojas/new">Cadastrar Loja</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Procurar">
        </div>
        <button type="submit" class="btn btn-default">Confirmar</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>

        <li><%= link_to "Deslogar", destroy_user_session_path, :method => :delete %></li>

      <% else %>
       
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/users/sign_in">Login para Usuários</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/lojas">Login para Lojas</a></li>
            </ul>
          </li>

      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


    <%= yield %>
  </body>
</html>

EP3/app/views/lojas/_form.html.erb
<%= simple_form_for @loja do |f|%>

  <%= f.input :nome, label: "Nome da loja" %>
  <%= f.input :descricao%>
  <%= f.input :email %>
  <%= f.button :submit %>

<% end %>

EP3/app/views/lojas/edit.html.erb
<h1>Editar Loja</h1>

<%= render 'form' %>

EP3/app/views/lojas/index.html.erb
<h1><b> <%= "Lojas disponíveis" %> </b></h1>

<% @lojas.each do |loja| %>
<h2> <%= link_to loja.nome, loja_path(loja) %></h2>

<% end %>

<%= link_to "Criar Loja", new_loja_path%>

EP3/app/views/lojas/new.html.erb
<h1> Nova Loja</h1>

<%= render 'form' %>

EP3/app/views/lojas/show.html.erb
<h2><%= @loja.nome %></h2>
<h3><%= @loja.email %></h3>

<p><%= @loja.descricao %></p>

<h3>Avaliação</h3>
<div class="average-review-rating" data-score=<%= @average_review %>></div>
<span>Em um total de <%= @loja.reviews.count %> avaliações.</span>

<%=link_to "Voltar", loja_path %>
<%=link_to "Editar", edit_loja_path(@loja) %>
<%= link_to "Deletar", loja_path(@loja), method: :delete, data: {confirm: "Tem certeza?"} %>
<%= link_to "Reclamar",  new_loja_review_path(@loja) %>

<%= render @loja.reviews.reverse %>

<script>
	$('.review-rating').raty({

		readOnly: true,
		score: function(){
			return $(this).attr('data-score');
		},
		path: '/assets/'

	});
</script>

<script>
	
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function(){
			return $(this).attr('data-score')
		}
	});

</script>

EP3/app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :comentario %>
    <%= f.input :data %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

EP3/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

EP3/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Comentario</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.comentario %></td>
        <td><%= post.data %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

EP3/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

EP3/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @post.comentario %>
</p>

<p>
  <strong>Data:</strong>
  <%= @post.data %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

EP3/app/views/reviews/_form.html.erb
<%= simple_form_for([@loja, @loja.reviews.build]) do |f| %>

	<div id="rating-form">
		<label>Avaliação:<label>
	</div>

	<%= f.input :comment %>
	<%= f.button :submit %>
<% end %>

<script>

$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>

EP3/app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %></p>

<% if user_signed_in? %>

	<% if review.user_id == current_user.id %>

<%= link_to  "Editar", edit_loja_review_path(review.loja, review) %>
<%= link_to  "Delete", loja_review_path(review.loja, review), :method => :delete, data: { confirm: "Tem certeza?"}%>
	<% end %>

<% end %>

EP3/app/views/reviews/edit.html.erb
<h1>Editando Reclamação</h1>

<%= simple_form_for([@loja, @review]) do |f|%>

	<div id="rating-form">
		<label>Avaliação:<label>
	</div>
	
	<%= f.input :comment %>
	<%= f.button :submit %>	

<% end %>


<script>

$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>

EP3/app/views/reviews/new.html.erb
<h1>Nova Reclamação</h1>

<%= render 'form' %>